pool:
    vmImage: 'ubuntu-20.04'
variables:
    BUILD_NUMBER: $[counter('buildCounter',1)]
    NUGET_REPO_URL: https://api.nuget.org/v3/index.json
    
trigger:
    branches:
        include:
        - master
        - refs/tags/*
steps:
    - task: UseDotNet@2
      inputs:
        version: '6.0.100'

    - task: DotNetCoreCLI@2
      displayName: "Restore tools"
      inputs:
        command: custom
        custom: tool
        arguments: restore

    - task: DotNetCoreCLI@2
      displayName: "Build"
      inputs:
        command: custom
        custom: fsi
        arguments: build.fsx
